version: '3.5'
services:
  mongodb:
    container_name: mongo_urlshortener
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - mongo.env
    volumes:
      - /Users/databackup/mongodb_data_volume/db:/data/db
      - /Users/databackup/mongodb_data_volume/log:/var/log/mongodb
      - ./init.d:/docker-entrypoint-initdb.d
